version: '2.3'

services:

  elastic:
    image: elasticsearch:7.9.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - logger.level=error
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      interval: 5s
      retries: 500
      test: curl -s 127.0.0.1:9200 &>/dev/null
    ## Uncomment the next lines if index should persist on disk
    #volumes:
    #  - data01:/usr/share/elasticsearch/datacd rep
    ## Uncomment the next line when deploying in production.
    #restart: always
  kibana:
    image: kibana:7.9.1
    ports:
      - "5601:5601"
    environment:
      SERVER_BASEPATH: /eisp
      SERVER_REWRITEBASEPATH: "true"
      ELASTICSEARCH_HOSTS: http://elastic:9200
    depends_on:
      elastic:
        condition: service_healthy
    ## Uncomment the next line when deploying in production.
    #restart: always

  eisp:
    image: cceh/eisp:latest
    depends_on:
      elastic:
        condition: service_healthy
        
    ## Uncomment the next line when deploying in production.
    #restart: always
    ## volumes:
    ##   - PATH_TO_EISP_INI_FILE:/etc/eisp.ini:ro
    ##   - PATH_TO_ELASTIC_MAPPING_AND_SETTINGS:/etc/eisp.ini:ro
    ##   - PATH_TO_PDF_FILES:/var/lib/eisp:ro
    volumes:
      - ./eisp.ini:/etc/eisp.ini:ro
      - ./elastic_mapping.json:/etc/elastic_mapping.json:ro
      - /opt/taeter/mnt/mbi-cloud/Archive:/var/lib/eisp:ro
    
    command: [--config_file, /etc/eisp.ini]    

## Uncomment the next lines if index should persist on disk
#volumes:
#  data01:
#    driver: local